[project]
name = "jupyterlite-sphinx"
description = "Sphinx extension for deploying JupyterLite"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
authors = [
    { name = "JupyterLite Contributors" },
]